### ISSUE TITLE
macOS .DS_Store Files are not filtered from dataset

### ISSUE THREAD

**Issue by Acasteo** [mist-medical/MIST#33]
**Describe the bug**
The .DS_Store file generated by the Finder in macOS appears in fg_bboxes csv as an image

**To Reproduce**
Run mist_analyze with a train dataset directory including a .DS_Store.

**Expected behavior**
The .DS_Store file is filtered and ignored.

**Screenshots**
![Screenshot 2024-09-13 at 3 21 08 PM](https://github.com/user-attachments/assets/bcf88eeb-a6b2-4725-90a3-3744690e5c2a)

**Hardware/software stack (please complete the following information):**
 - OS: Any assuming data folder contains .DS_Store

**Comment by aecelaya** [comment]
Thanks for pointing this out! I pushed an update to fix this issue.
