### ISSUE TITLE
Crash occurs during analysis if dataset has a patient with invalid label set on most recent version

### ISSUE THREAD

**Issue by evanmlim** [mist-medical/MIST#37]
**Describe the bug**
Patients with an invalid label set should be excluded from the final dataset during analysis. To test, I purposely added an extra patient to the CHAOS dataset with a labels [0, 2] instead of [0, 1] when the defined labels are [0, 1]. However, the analysis crashed instead of excluding the erroneous patient. I presume it's any invalid patient, not just patients with an invalid label set.

**To Reproduce**
Run mist_analyze on any dataset with at least 1 patient with a set of labels that isn't a subset of the labels described in the --data .json file. 

**Screenshots**
The crash log is as follows:
![image](https://github.com/user-attachments/assets/ffb1f11c-172d-4323-b4dd-c26ea2467b13)

**Comment by aecelaya** [comment]
Thanks for finding that bug!

I know that the exclusion of bad cases works. Try running it on the raw LiTS dataset, and you'll see that it excludes two cases for header mismatches. I think this specific corner case might cause a crash somewhere.

**Comment by aecelaya** [comment]
This bug was fixed in the latest release (v0.1.2-beta). We forgot to reset the index in the paths dataframe when we dropped rows that corresponded to bad data.

BTW this was why your total seg cluster 0 job was failing.
